AWSTemplateFormatVersion: '2010-09-09'
Description: Generates Xebia Email Signature
Resources:
  App:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: xebia-email-signature
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: 444093529715.dkr.ecr.eu-west-1.amazonaws.com/xebia-email-signature:0.0.0-286cdfa
          ImageRepositoryType: ECR
        AutoDeploymentsEnabled: false
        AuthenticationConfiguration:
          AccessRoleArn: !GetAtt AppRunnerRole.Arn
      InstanceConfiguration:
        Cpu: '1024'
        Memory: '2048'
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: /

  AppRunnerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - build.apprunner.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: ECRAccessPermission
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                Resource:
                  - '*'
              - Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:DescribeImages
                  - ecr:BatchCheckLayerAvailability
                Resource:
                  - !Sub 'arn:aws:ecr:*:${AWS::AccountId}:repository/xebia-email-signature'

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        # Aliases:
        #   - signature.xebia.com
        #   - signature.oblcc.com
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            - PUT
            - PATCH
            - POST
            - DELETE
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true
          TargetOriginId: xebiasignatureprodDistributionOrigin153FD91E6
          ViewerProtocolPolicy: allow-all
        Enabled: true
        HttpVersion: http2and3
        IPV6Enabled: true
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
            DomainName: !GetAtt App.ServiceUrl
            Id: xebiasignatureprodDistributionOrigin153FD91E6
        PriceClass: PriceClass_All
        Restrictions:
          GeoRestriction:
            Locations:
              - RU
              - CN
            RestrictionType: blacklist